### ISSUE TITLE
TeXのコンパイル失敗時、過去のPDFが吐き出される場合がある。

### ISSUE THREAD

**Issue by gw31415** [mathlava/gartbot#17]
TeXのコンパイルが失敗した時、過去のPDFが吐き出される場合がある。

過去のPDFが削除されていないところにPDFの上書きが行われないためと思われます。

**Comment by gw31415** [comment]
多分command_texの54行目に

```py
subprocess.run(['rm', '/tmp/' + fid + '.*'])
```

これ入れればtexについては治る…？

**Comment by Gart2357** [comment]
```py
subprocess.run(f'rm /tmp/{fid}.*', shell=True)
```
じゃないと動かないと思うけどやろうとしてた

**Comment by gw31415** [comment]
そだわ、アレだとワイルドカード展開されないな。
ごめんごめん

**Comment by Gart2357** [comment]
完全に理解した
uplatex のエラー処理もすれば大丈夫そう

**Comment by Gart2357** [comment]
uplatex の returncode 正常でも 0 返さないんだが()

**Comment by gw31415** [comment]
あー、うろ覚えだがそんな謎仕様だった気がするお

**Comment by Gart2357** [comment]
そんなことなかったかもしれない
